name = "lubulu-api"
main = "index.js"
compatibility_date = "2024-01-01"

# 环境变量
[vars]
ENVIRONMENT = "production"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "lubulu-db"
database_id = "your-database-id"

# KV 命名空间 (可选，用于缓存)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-id"

# Secrets (通过 wrangler secret put 设置)
# JWT_SECRET = "your-secret-key"

[build]
command = ""

# 开发环境配置
[env.dev]
name = "lubulu-api-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置
[env.production]
name = "lubulu-api"
routes = [
  { pattern = "api.lubulu.app/*", zone_name = "lubulu.app" }
]
