name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'workers/api/**'
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL != '' && secrets.VITE_API_URL || 'https://api.lubulu.app' }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lubulu
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Pages deployed successfully!"
          echo "🌐 Site is now live!"
